build:
  project: build.proj
  verbosity: normal

deploy:
  - provider: NuGet
    api_key:
      secure: zfW76Poy+HwwoepzS5TFy+6RJdGaS8tOCMRRv1yvPGe7UCtMn4KDAm3rskXgrPas
    artifact: Packages
    on:
      branch: master
      appveyor_repo_tag: true
      
nuget:
  project_feed: true
  disable_publish_on_pr: true
  
artifacts:
  - path: '*.nupkg'
    name: Packages